(()=>{'use strict';
const $=s=>document.querySelector(s),video=$('#video'),canvas=$('#canvas'),ctx=canvas.getContext('2d'),empty=$('#empty'),hint=$('#hint'),result=$('#result');
const W=240,HH=320,WIDTHS={singles:5.18,doubles:6.10},labels=['近端左角（底线）','近端右角（底线）','远端右角（中线）','远端左角（中线）'];
const proc=document.createElement('canvas');proc.width=W;proc.height=HH;const pc=proc.getContext('2d',{willReadFrequently:true});
let mode='empty',playMode=null,points=[],H=null,Hi=null,stream=null,raf=0,frameW=0,frameH=0,samples=[],detectFrames=0,url=null,dragIndex=-1;
const v={prev:null,track:[],candidate:null,missing:0,armed:true,quiet:0,landing:null,lastAt:0,fallbackFrames:0,confidence:0};
const recognition=document.createElement('div');recognition.className='recognition';recognition.innerHTML='<b id="recognitionMode">外形验证待命</b><span class="shapeMeter"><i id="confidenceBar"></i></span><span id="confidenceText">—</span>';document.querySelector('.status').after(recognition);const shapeStyle=document.createElement('style');shapeStyle.textContent='.recognition{display:grid;grid-template-columns:auto 1fr auto;gap:7px;align-items:center;margin:8px 2px 0;padding:8px 10px;border:1px solid var(--line);border-radius:11px;background:#0b1b14;color:var(--muted);font-size:10px}.recognition b{color:#dfffee}.shapeMeter{height:4px;border-radius:5px;background:#294338;overflow:hidden}.shapeMeter i{display:block;width:0;height:100%;background:var(--mint);transition:width .15s}.recognition.fallback b,.recognition.fallback #confidenceText{color:var(--yellow)}.recognition.fallback .shapeMeter i{background:var(--yellow)}';document.head.append(shapeStyle);
const chooser=$('#gameDialog');shapeStyle.textContent+='.badge{border:0}.gameDialog{position:fixed;z-index:99;inset:0;display:grid;place-items:center;padding:22px;background:#020906e8;backdrop-filter:blur(12px)}.gameDialog[hidden]{display:none}.gameDialogCard{width:min(100%,390px);padding:25px 20px 20px;border:1px solid #376b55;border-radius:24px;background:linear-gradient(160deg,#163626,#0b1b14 70%);box-shadow:0 24px 70px #000b;text-align:center}.gameIcon{font-size:38px}.gameDialogCard>p{margin:11px 0 4px;color:var(--mint);font-size:11px;letter-spacing:.12em}.gameDialogCard h2{margin:0;font-size:22px}.gameDialogCard>small{display:block;margin:9px 0 18px;color:var(--muted);line-height:1.55}.gameDialogCard>div:last-child{display:grid;grid-template-columns:1fr 1fr;gap:10px}.gameDialogCard .btn{display:grid;gap:4px;padding:15px 7px}.gameDialogCard .btn b{font-size:17px}.gameDialogCard .btn span{font-size:10px;font-weight:400;opacity:.8}';
function selectPlayMode(next){if(mode!=='empty')stop();playMode=next;$('#modeBadge').textContent=next==='singles'?'单打 · 内边线':'双打 · 外边线';chooser.hidden=true;$('#cameraBtn').disabled=false;status(`已选择${next==='singles'?'单打':'双打'}，可启动摄像头`);ui()}chooser.onclick=e=>{const next=e.target.closest('[data-play]')?.dataset.play;if(next)selectPlayMode(next)};$('#modeBadge').onclick=()=>{chooser.hidden=false};$('#cameraBtn').disabled=true;
function recognitionUI(kind='ready',confidence=0){const names={ready:'外形验证已就绪',verified:'已识别羽毛球外形',fallback:'仅运动候选（后备）',idle:'外形验证待命'};recognition.classList.toggle('fallback',kind==='fallback');$('#recognitionMode').textContent=names[kind];$('#confidenceBar').style.width=`${Math.round(confidence*100)}%`;$('#confidenceText').textContent=kind==='idle'?'—':`${Math.round(confidence*100)}%`}
function rect(){const w=canvas.clientWidth,h=canvas.clientHeight;if(!frameW)return{x:0,y:0,w,h};const s=Math.min(w/frameW,h/frameH),rw=frameW*s,rh=frameH*s;return{x:(w-rw)/2,y:(h-rh)/2,w:rw,h:rh}}
function pv(p){const m=rect();return{x:m.x+p.x/W*m.w,y:m.y+p.y/HH*m.h}}function vp(p){const m=rect();return{x:(p.x-m.x)/m.w*W,y:(p.y-m.y)/m.h*HH}}
function size(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}addEventListener('resize',size);new ResizeObserver(size).observe(canvas);
function status(s,c=''){$('#statusText').textContent=s;$('#lamp').className='lamp '+c}function step(a,b,c){$('#stepTitle').textContent=a;$('#stepDesc').textContent=b;$('#counter').textContent=c}
function ui(){const manual=mode==='manual',adjust=mode==='adjust';$('#calibrateBtn').disabled=mode==='empty';$('#calibrateBtn').textContent=mode==='monitor'?'调整边界':'手动校准';$('#stopBtn').disabled=mode==='empty';$('#retryBtn').disabled=mode==='empty'||manual||adjust;$('#undoBtn').disabled=!manual||!points.length;hint.style.display=manual||adjust?'block':'none';if(mode==='empty')step('准备机位','只需让本侧底线、两条边线及球网线清晰可见；不需要远端底线。','未启动');if(mode==='detect')step('自动识别边界','保持手机固定，正在寻找四条半场边界。','分析中');if(manual){step('手动校准',`点击${labels[points.length]||'完成'}`,`${points.length} / 4`);hint.innerHTML=`手动校准 ${points.length+1}/4　<b>${labels[points.length]||''}</b>`}if(adjust){step('调整识别边界','拖动黄色角点贴合真实场线，松手立即生效。','可编辑');hint.innerHTML='拖动任一<b>黄色角点</b>微调边界'}if(mode==='monitor')step('正在监测','已使用识别边界；如不准确可点“调整边界”。','实时');draw()}
async function camera(){if(!playMode){status('请先选择单打或双打','warn');return}try{stopMedia();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:1920},aspectRatio:{ideal:.75}},audio:false});video.srcObject=stream;await video.play();start()}catch(e){status('无法打开摄像头','warn');alert('无法打开摄像头。请使用 HTTPS/localhost，允许摄像头权限。')}}
function start(){frameW=video.videoWidth||720;frameH=video.videoHeight||1280;empty.style.display='none';retry();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}function stopMedia(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(url){URL.revokeObjectURL(url);url=null}cancelAnimationFrame(raf)}
function stop(){stopMedia();video.removeAttribute('src');video.srcObject=null;mode='empty';points=[];H=Hi=null;empty.style.display='grid';result.style.display='none';status('监测已停止');recognitionUI('idle');ui()}
function resetVision(){Object.assign(v,{prev:null,track:[],candidate:null,missing:0,armed:true,quiet:0,landing:null,lastAt:0,fallbackFrames:0,confidence:0});recognitionUI(mode==='empty'?'idle':'ready',0)}
function manual(){mode='manual';points=[];H=Hi=null;samples=[];resetVision();status(`请标记${playMode==='singles'?'单打内边线':'双打外边线'}四角`,'warn');ui()}function adjust(){if(points.length!==4)return manual();mode='adjust';resetVision();status('正在调整识别边界，拖动角点后松手','warn');ui()}function retry(){mode='detect';points=[];H=Hi=null;samples=[];detectFrames=0;resetVision();status(`正在识别${playMode==='singles'?'单打':'双打'}半场边界`,'warn');ui()}
$('#cameraBtn').onclick=camera;$('#stopBtn').onclick=stop;$('#calibrateBtn').onclick=()=>mode==='monitor'?adjust():manual();$('#retryBtn').onclick=retry;$('#undoBtn').onclick=()=>{points.pop();ui()};$('#file').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!playMode){status('请先选择单打或双打','warn');chooser.hidden=false;e.target.value='';return}stopMedia();url=URL.createObjectURL(f);video.srcObject=null;video.src=url;video.onloadedmetadata=()=>video.play().then(start)};
function eventPoint(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.onpointerdown=e=>{if(mode!=='adjust')return;const p=eventPoint(e);dragIndex=points.reduce((best,q,i)=>Math.hypot(q.x-p.x,q.y-p.y)<Math.hypot(points[best].x-p.x,points[best].y-p.y)?i:best,0);if(Math.hypot(points[dragIndex].x-p.x,points[dragIndex].y-p.y)>32)dragIndex=-1;else canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{if(mode!=='adjust'||dragIndex<0)return;const p=eventPoint(e),m=rect();points[dragIndex]={x:Math.max(m.x,Math.min(m.x+m.w,p.x)),y:Math.max(m.y,Math.min(m.y+m.h,p.y))};draw()};
canvas.onpointerup=e=>{if(mode==='adjust'&&dragIndex>=0){const q=points.map(vp);dragIndex=-1;if(validateQuad(q))apply(q,'边界调整');else{status('调整后边界形状无效，请继续拖动','warn');mode='adjust';ui()}return}if(mode!=='manual')return;const p=eventPoint(e),m=rect();if(p.x<m.x||p.x>m.x+m.w||p.y<m.y||p.y>m.y+m.h)return;points.push(p);if(points.length===4){const q=points.map(vp);if(validateQuad(q))apply(q,'手动校准');else{points.pop();status('角点顺序或形状无效，请重试最后一点','warn')}}ui()};
function loop(t){if(video.readyState>=2&&!video.paused){pc.drawImage(video,0,0,W,HH);const im=pc.getImageData(0,0,W,HH);if(mode==='detect')auto(im);}draw();if(mode!=='empty')raf=requestAnimationFrame(loop)}
function auto(im){detectFrames++;let q=detectCourt(im.data,W,HH);if(q&&playMode==='singles')q=insetSingles(q);if(q)samples.push(q);else if(samples.length)samples.shift();if(samples.length>=7){const avg=[0,1,2,3].map(i=>({x:samples.slice(-7).reduce((s,q)=>s+q[i].x,0)/7,y:samples.slice(-7).reduce((s,q)=>s+q[i].y,0)/7}));if(validateQuad(avg))apply(avg,'自动识别')}if(detectFrames===150){mode='detect-failed';status('未识别到稳定边界，请重试或手动校准','warn');step('未识别到稳定边界','改善光线、避开反光或遮挡后重试；也可手动标记四角。','需要确认');$('#retryBtn').disabled=false}}
function insetSingles(q){const r=.46/6.10;return[q[0],q[1],q[2],q[3]].map((p,i)=>{const mate=i===0?q[1]:i===1?q[0]:i===2?q[3]:q[2];return{x:p.x+(mate.x-p.x)*r,y:p.y+(mate.y-p.y)*r}})}
function detectCourt(data,w,h){const rows=[];for(let y=h*.16|0;y<h-3;y+=4){const xs=[];for(let x=2;x<w-2;x++){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(mx>145&&mx-mn<55&&r+g+b>500)xs.push(x)}if(xs.length>=4){const l=pct(xs,.08),rr=pct(xs,.92);if(rr-l>w*.18)rows.push({y,l,r:rr})}}if(rows.length<16)return null;const farRows=rows.filter(a=>a.y<h*.58&&a.y>h*.2),nearRows=rows.filter(a=>a.y>h*.58);if(farRows.length<6||nearRows.length<6)return null;const fy=pct(farRows.map(a=>a.y),.48),ny=Math.min(h*.94,pct(nearRows.map(a=>a.y),.82)),use=rows.filter(a=>a.y>=fy-12&&a.y<=ny+8),L=fit(use.map(a=>[a.y,a.l])),R=fit(use.map(a=>[a.y,a.r]));if(!L||!R)return null;return [[at(L,ny),ny],[at(R,ny),ny],[at(R,fy),fy],[at(L,fy),fy]].map(([x,y])=>({x,y}))}
function pct(a,p){const s=[...a].sort((x,y)=>x-y);return s[Math.min(s.length-1,Math.floor((s.length-1)*p))]}function fit(ps){if(ps.length<5)return null;let sx=0,sy=0,sxx=0,sxy=0;for(const[y,x]of ps){sx+=y;sy+=x;sxx+=y*y;sxy+=y*x}const n=ps.length,d=n*sxx-sx*sx;return Math.abs(d)<1e-6?null:{a:(n*sxy-sx*sy)/d,b:(sy*sxx-sx*sxy)/d}}function at(l,y){return l.a*y+l.b}
function validateQuad(q){if(!q||q.length!==4||q.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y)))return false;const area=Math.abs(q.reduce((s,p,i)=>s+p.x*q[(i+1)%4].y-p.y*q[(i+1)%4].x,0))/2;return area>W*HH*.045&&q[0].x<q[1].x&&q[3].x<q[2].x&&q[0].y>q[3].y&&q[1].y>q[2].y}
function court(){const width=WIDTHS[playMode]||WIDTHS.singles;return[[0,6.7],[width,6.7],[width,0],[0,0]]}function apply(q,kind){H=homography(court(),q.map(p=>[p.x,p.y]));Hi=H&&inv(H);if(!Hi)return manual();points=q.map(pv);mode='monitor';resetVision();status(`${kind}完成 · ${playMode==='singles'?'单打':'双打'}边界已就绪`,'live');ui()}
function track(im,t){const gray=new Uint8Array(W*HH),mask=new Uint8Array(W*HH),courtWidth=WIDTHS[playMode];for(let i=0,j=0;i<im.data.length;i+=4,j++)gray[j]=(im.data[i]*3+im.data[i+1]*6+im.data[i+2])/10;if(!v.prev){v.prev=gray;return}for(let y=5;y<HH-5;y++)for(let x=3;x<W-3;x++){const i=y*W+x;if(Math.abs(gray[i]-v.prev[i])>38){const c=map(Hi,x,y);if(c.x>-.9&&c.x<courtWidth+.9&&c.y>-.9&&c.y<7.6)mask[i]=1}}const shapes=components(mask,gray,im.data),last=v.track.at(-1);let best=null,bestRank=-1;for(const s of shapes){const continuity=last?Math.max(0,1-Math.hypot(s.x-last.x,s.y-last.y)/75):.65,rank=s.confidence*.78+continuity*.22;if(rank>bestRank){bestRank=rank;best={...s,t,c:map(Hi,s.x,s.y)}}}v.prev=gray;
 if(best&&best.confidence>=.48){v.fallbackFrames=0;acceptTrack(best);recognitionUI('verified',best.confidence)}else if(best&&best.confidence>=.25&&++v.fallbackFrames>=3){acceptTrack(best);recognitionUI('fallback',best.confidence)}else{missTrack();recognitionUI(best?'fallback':'ready',best?.confidence||0)}}
function acceptTrack(best){const last=v.track.at(-1);best.head=chooseHead(best,last);best.headCourt=map(Hi,best.head.x,best.head.y);v.missing=0;v.quiet=0;v.confidence=best.confidence;v.track.push(best);if(v.track.length>12)v.track.shift();landingCandidate()}
function missTrack(){v.missing++;v.quiet++;if(v.candidate&&v.missing>=2)confirm(v.candidate);if(v.quiet>28){v.track=[];v.candidate=null;v.armed=true;v.fallbackFrames=0}}
function components(mask,gray,rgba){const seen=new Uint8Array(mask.length),out=[];for(let y=4;y<HH-4;y+=2)for(let x=3;x<W-3;x+=2){const start=y*W+x;if(!mask[start]||seen[start])continue;const stack=[start],pixels=[];seen[start]=1;let minX=x,maxX=x,minY=y,maxY=y;while(stack.length&&pixels.length<180){const i=stack.pop(),px=i%W,py=i/W|0;pixels.push(i);minX=Math.min(minX,px);maxX=Math.max(maxX,px);minY=Math.min(minY,py);maxY=Math.max(maxY,py);for(const n of [i-1,i+1,i-W,i+W])if(n>0&&n<mask.length&&mask[n]&&!seen[n]){seen[n]=1;stack.push(n)}}if(pixels.length>=2&&pixels.length<=150){const f=shapeFeatures(pixels,gray,rgba,{minX,maxX,minY,maxY});if(f)out.push(f)}}return out.sort((a,b)=>b.confidence-a.confidence).slice(0,12)}
function shapeFeatures(pixels,gray,rgba,b){const bw=b.maxX-b.minX+1,bh=b.maxY-b.minY+1;if(bw>28||bh>34||bw*bh>500)return null;let sx=0,sy=0,bright=0,white=0,top=0,bottom=0;for(const i of pixels){const x=i%W,y=i/W|0;sx+=x;sy+=y;if(gray[i]>155)bright++;const j=i*4,mx=Math.max(rgba[j],rgba[j+1],rgba[j+2]),mn=Math.min(rgba[j],rgba[j+1],rgba[j+2]);if(mx>150&&mx-mn<62)white++;if(y<(b.minY+b.maxY)/2)top++;else bottom++}const center={x:sx/pixels.length,y:sy/pixels.length},shape=principalEndpoints(pixels,center),features={area:pixels.length,width:bw,height:bh,bright:bright/pixels.length,white:white/pixels.length,fill:pixels.length/(bw*bh),taper:shape.taper,aspect:bh/bw};return{x:center.x,y:center.y,box:b,ends:shape.ends,appearanceHead:shape.head,features,confidence:shapeScore(features)}}
function principalEndpoints(pixels,c){let xx=0,yy=0,xy=0;for(const i of pixels){const dx=i%W-c.x,dy=(i/W|0)-c.y;xx+=dx*dx;yy+=dy*dy;xy+=dx*dy}const angle=.5*Math.atan2(2*xy,xx-yy),ax={x:Math.cos(angle),y:Math.sin(angle)},perp={x:-ax.y,y:ax.x};let lo=Infinity,hi=-Infinity,loWidth=0,hiWidth=0,ln=0,hn=0;const projected=[];for(const i of pixels){const dx=i%W-c.x,dy=(i/W|0)-c.y,p=dx*ax.x+dy*ax.y,q=Math.abs(dx*perp.x+dy*perp.y);projected.push([p,q]);lo=Math.min(lo,p);hi=Math.max(hi,p)}const mid=(lo+hi)/2;for(const[p,q]of projected)if(p<mid){loWidth+=q;ln++}else{hiWidth+=q;hn++}loWidth/=ln||1;hiWidth/=hn||1;const ends=[{x:c.x+ax.x*lo,y:c.y+ax.y*lo},{x:c.x+ax.x*hi,y:c.y+ax.y*hi}],head=loWidth<=hiWidth?ends[0]:ends[1];return{ends,head,taper:Math.min(1,Math.abs(loWidth-hiWidth)/Math.max(.5,loWidth+hiWidth))}}
function chooseHead(s,last){if(last&&s.ends){const dx=s.x-last.x,dy=s.y-last.y;if(Math.hypot(dx,dy)>1.3)return s.ends.reduce((a,b)=>(a.x-s.x)*dx+(a.y-s.y)*dy>(b.x-s.x)*dx+(b.y-s.y)*dy?a:b)}return s.appearanceHead||{x:s.x,y:s.y}}
function shapeScore(f){const size=f.area>=3&&f.area<=90?1:f.area<3?.2:Math.max(0,1-(f.area-90)/60),aspect=f.aspect>=.45&&f.aspect<=3.8?1:Math.max(0,1-Math.abs(f.aspect-1.5)/3),fill=f.fill>=.12&&f.fill<=.78?1:.35,brightness=Math.min(1,(f.bright*.6+f.white*.4)/.62),taper=Math.min(1,f.taper/.34),base=size*.2+aspect*.13+fill*.12+brightness*.36+taper*.19;return Math.max(0,Math.min(1,base*(.5+.5*brightness)*(.55+.45*taper)))}
function landingCandidate(){if(!v.armed||v.track.length<5)return;const a=v.track[v.track.length-5],b=v.track.at(-1),p=v.track[v.track.length-2],p2=v.track[v.track.length-3];if(b.y-a.y>5&&b.y-p.y<Math.max(2,(p2.y-a.y)*.65)&&b.c.y>-.7&&b.c.y<7.4)v.candidate=b}
function inside(p,t=.06,width=WIDTHS[playMode]||WIDTHS.singles){return p.x>=-t&&p.x<=width+t&&p.y>=-t&&p.y<=6.7+t}function classifyHead(p,t=.06,width=WIDTHS[playMode]||WIDTHS.singles){const strict=p.x>=0&&p.x<=width&&p.y>=0&&p.y<=6.7;if(strict)return'inside';return inside(p,t,width)?'line':'outside'}function confirm(p){if(!v.armed)return;v.candidate=null;v.armed=false;const head=p.head||{x:p.x,y:p.y},court=p.headCourt||map(Hi,head.x,head.y),decision=classifyHead(court),ok=decision!=='outside';v.landing={p,head,court,decision,ok};result.className='result '+(ok?'in':'out');result.innerHTML=`<strong>${decision==='outside'?'OUT':decision==='line'?'压 线':'界 内'}</strong>${playMode==='singles'?'单打内边线':'双打外边线'} · ${decision==='line'?'球头距边界不超过 6 cm，按界内':decision==='inside'?'球头首次接触点在半场内':'球头首次接触点在半场外'}`;result.style.display='block';setTimeout(()=>result.style.display='none',2600);if(!ok&&'speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance('Out');u.lang='en-US';u.rate=1.05;speechSynthesis.speak(u)}}
function solve(A,b){A=A.map(r=>[...r]);b=[...b];for(let i=0;i<b.length;i++){let m=i;for(let j=i+1;j<b.length;j++)if(Math.abs(A[j][i])>Math.abs(A[m][i]))m=j;[A[i],A[m]]=[A[m],A[i]];[b[i],b[m]]=[b[m],b[i]];const d=A[i][i];if(Math.abs(d)<1e-9)return null;for(let k=i;k<A[i].length;k++)A[i][k]/=d;b[i]/=d;for(let j=0;j<b.length;j++)if(j!==i){const f=A[j][i];for(let k=i;k<A[j].length;k++)A[j][k]-=f*A[i][k];b[j]-=f*b[i]}}return b}function homography(src,dst){let A=[],b=[];for(let i=0;i<4;i++){const[x,y]=src[i],[u,z]=dst[i];A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-z*x,-z*y]);b.push(z)}const h=solve(A,b);return h&&[...h,1]}function inv(M){const[a,b,c,d,e,f,g,h,i]=M,A=e*i-f*h,B=c*h-b*i,C=b*f-c*e,D=f*g-d*i,E=a*i-c*g,F=c*d-a*f,G=d*h-e*g,H=b*g-a*h,I=a*e-b*d,det=a*A+b*D+c*G;return Math.abs(det)<1e-9?null:[A,B,C,D,E,F,G,H,I].map(x=>x/det)}function map(M,x,y){const z=M[6]*x+M[7]*y+M[8];return{x:(M[0]*x+M[1]*y+M[2])/z,y:(M[3]*x+M[4]*y+M[5])/z}}
function draw(){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);if(points.length){ctx.lineWidth=3;ctx.strokeStyle='#62f5b2';ctx.fillStyle='#ffd166';ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(points.length===4)ctx.closePath();ctx.stroke();points.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,6,0,7);ctx.fill();ctx.fillStyle='#07130f';ctx.font='bold 9px sans-serif';ctx.textAlign='center';ctx.fillText(i+1,p.x,p.y+3);ctx.fillStyle='#ffd166'})}if(v.track.length&&mode==='monitor'){const s=v.track.at(-1),p=pv(s),head=pv(s.head||s);ctx.strokeStyle='#ffd166';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,8,0,7);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(head.x,head.y,3,0,7);ctx.fill()}if(v.landing){const p=pv(v.landing.head);ctx.strokeStyle=v.landing.ok?'#62f5b2':'#ff6b6b';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x-10,p.y);ctx.lineTo(p.x+10,p.y);ctx.moveTo(p.x,p.y-10);ctx.lineTo(p.x,p.y+10);ctx.stroke()}}
inside=(p,t=.06)=>{const width=WIDTHS[playMode]||WIDTHS.singles;return p.x>=-t&&p.x<=width+t&&p.y>=-t&&p.y<=6.7+t};classifyHead=(p,t=.06)=>{const width=WIDTHS[playMode]||WIDTHS.singles,strict=p.x>=0&&p.x<=width&&p.y>=0&&p.y<=6.7;return strict?'inside':inside(p,t)?'line':'outside'};
window.__lineJudge={solve,homography,inv,map,inside,classifyHead,validateQuad,fit,shapeScore,shapeFeatures,principalEndpoints,chooseHead,setPlayModeForTest:n=>playMode=n};recognitionUI('idle');ui();size();})();

